import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import assert from 'node:assert/strict'

const root = process.cwd()

test('app router shell and first public routes are present', () => {
  const appAdminPage = fs.readFileSync(path.join(root, 'app/admin/page.js'), 'utf8')
  const appLayout = fs.readFileSync(path.join(root, 'app/layout.js'), 'utf8')
  const appCartPage = fs.readFileSync(path.join(root, 'app/cart/page.js'), 'utf8')
  const appCataloguePage = fs.readFileSync(path.join(root, 'app/catalogue/page.js'), 'utf8')
  const appCatalogueTrackPage = fs.readFileSync(path.join(root, 'app/catalogue/[trackId]/page.js'), 'utf8')
  const appHomePage = fs.readFileSync(path.join(root, 'app/page.js'), 'utf8')
  const appProfilePage = fs.readFileSync(path.join(root, 'app/profile/page.js'), 'utf8')
  const appProfileTrackPage = fs.readFileSync(path.join(root, 'app/profile/[trackId]/page.js'), 'utf8')
  const appSignInPage = fs.readFileSync(path.join(root, 'app/auth/signin/page.js'), 'utf8')
  const appUploadPage = fs.readFileSync(path.join(root, 'app/upload/page.js'), 'utf8')
  const providers = fs.readFileSync(path.join(root, 'components/providers/AppProviders.js'), 'utf8')

  assert.match(appAdminPage, /getServerSession/)
  assert.match(appAdminPage, /AdminConsoleContent/)
  assert.match(appAdminPage, /force-dynamic/)
  assert.match(appLayout, /AppProviders/)
  assert.match(appLayout, /metadata/)
  assert.match(appCartPage, /CartPageContent/)
  assert.match(appCataloguePage, /publicTrackWhere/)
  assert.match(appCataloguePage, /CataloguePageContent/)
  assert.match(appCatalogueTrackPage, /notFound/)
  assert.match(appCatalogueTrackPage, /CatalogueTrackDetailContent/)
  assert.match(appCatalogueTrackPage, /force-dynamic/)
  assert.match(appHomePage, /getServerSession/)
  assert.match(appHomePage, /redirect\('\/catalogue'\)/)
  assert.match(appProfilePage, /getServerSession/)
  assert.match(appProfilePage, /ProfilePageContent/)
  assert.match(appProfilePage, /force-dynamic/)
  assert.match(appProfileTrackPage, /canAccessFullTrack/)
  assert.match(appProfileTrackPage, /ProfileTrackDetailContent/)
  assert.match(appProfileTrackPage, /notFound/)
  assert.match(appSignInPage, /getServerSession/)
  assert.match(appSignInPage, /SignInPageContent/)
  assert.match(appUploadPage, /UploadForm/)
  assert.match(providers, /SessionProvider/)
  assert.match(providers, /CartProvider/)
  assert.match(providers, /Navbar/)
})
