import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import assert from 'node:assert/strict'

const root = process.cwd()

test('app router shell and first public routes are present', () => {
  const appAdminPage = fs.readFileSync(path.join(root, 'app/admin/page.js'), 'utf8')
  const appLayout = fs.readFileSync(path.join(root, 'app/layout.js'), 'utf8')
  const appCartPage = fs.readFileSync(path.join(root, 'app/cart/page.js'), 'utf8')
  const appCataloguePage = fs.readFileSync(path.join(root, 'app/catalogue/page.js'), 'utf8')
  const appCatalogueTrackPage = fs.readFileSync(path.join(root, 'app/catalogue/[trackId]/page.js'), 'utf8')
  const appHomePage = fs.readFileSync(path.join(root, 'app/page.js'), 'utf8')
  const appProfilePage = fs.readFileSync(path.join(root, 'app/profile/page.js'), 'utf8')
  const appSignInPage = fs.readFileSync(path.join(root, 'app/auth/signin/page.js'), 'utf8')
  const signInPageContent = fs.readFileSync(path.join(root, 'components/features/auth/SignInPageContent.js'), 'utf8')
  const appUploadPage = fs.readFileSync(path.join(root, 'app/upload/page.js'), 'utf8')
  const appUploadManagePage = fs.readFileSync(path.join(root, 'app/upload/manage/page.js'), 'utf8')
  const appUploadBatchDetailPage = fs.readFileSync(path.join(root, 'app/upload/manage/[batchId]/page.js'), 'utf8')
  const appUploadWorksDetailPage = fs.readFileSync(path.join(root, 'app/upload/manage/works/[collectionId]/page.js'), 'utf8')
  const appRequestPricingDecisionRoute = fs.readFileSync(path.join(root, 'app/api/track-requests/[requestId]/pricing-proposals/[proposalId]/route.js'), 'utf8')
  const providers = fs.readFileSync(path.join(root, 'components/providers/AppProviders.js'), 'utf8')

  assert.match(appAdminPage, /getServerSession/)
  assert.match(appAdminPage, /AdminConsoleContent/)
  assert.match(appAdminPage, /force-dynamic/)
  assert.match(appLayout, /AppProviders/)
  assert.match(appLayout, /metadata/)
  assert.match(appCartPage, /CartPageContent/)
  assert.match(appCataloguePage, /publicTrackWhere/)
  assert.match(appCataloguePage, /CataloguePageContent/)
  assert.match(appCatalogueTrackPage, /notFound/)
  assert.match(appCatalogueTrackPage, /CatalogueTrackDetailContent/)
  assert.match(appCatalogueTrackPage, /force-dynamic/)
  assert.match(appHomePage, /getServerSession/)
  assert.match(appHomePage, /redirect\('\/catalogue'\)/)
  assert.match(appProfilePage, /getServerSession/)
  assert.match(appProfilePage, /ProfilePageContent/)
  assert.match(appProfilePage, /force-dynamic/)
  assert.match(appSignInPage, /getServerSession/)
  assert.match(appSignInPage, /SignInPageContent/)
  assert.match(appSignInPage, /CMC_ENABLE_E2E_AUTH/)
  assert.match(signInPageContent, /Development sign in options/)
  assert.match(signInPageContent, /\/api\/e2e\/session/)
  assert.match(appUploadPage, /UploadForm/)
  assert.match(appUploadManagePage, /getServerSession/)
  assert.match(appUploadManagePage, /UploadManagementPageContent/)
  assert.match(appUploadManagePage, /force-dynamic/)
  assert.match(appUploadBatchDetailPage, /getServerSession/)
  assert.match(appUploadBatchDetailPage, /notFound/)
  assert.match(appUploadBatchDetailPage, /serializeUploadBatch/)
  assert.match(appUploadBatchDetailPage, /force-dynamic/)
  assert.match(appUploadWorksDetailPage, /getServerSession/)
  assert.match(appUploadWorksDetailPage, /getUserWorksCollection/)
  assert.match(appUploadWorksDetailPage, /notFound/)
  assert.match(appUploadWorksDetailPage, /force-dynamic/)
  assert.match(appRequestPricingDecisionRoute, /decideRequestPricingProposal/)
  assert.match(appRequestPricingDecisionRoute, /requireTrustedRouteOrigin/)
  assert.match(providers, /SessionProvider/)
  assert.match(providers, /CartProvider/)
  assert.match(providers, /Navbar/)
})
