# Some of the structure and code taken from 
# https://hub.docker.com/_/postgres/
# PostgreSQL Docker file documentation

version: '3.8'
services:
  # In Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@postgres/
  # In the App (.env)
  # - DATABASE_URL=postgres://prisma:prisma@localhost:5432/

  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
