ALTER TYPE "CatalogueReleaseStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "CatalogueReleaseStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';
ALTER TYPE "CatalogueReleaseStatus" ADD VALUE IF NOT EXISTS 'NEEDS_CHANGES';
ALTER TYPE "CatalogueReleaseStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
